#!/bin/sh
# postrm script
case "$1" in
  failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|1|2)
    ;;
  remove)
    rm -rf /opt/meteor
    ;;
  purge|0)
    rm -rf /opt/meteor
    userdel -rf meteor
    groupdel meteor
    ;;
  *)
    echo "postrm called with unknown argument: $1" >&2
    exit 1
    ;;
esac
