#!/bin/sh
# postrm script
case "$1" in
  failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|1|2)
    ;;
  remove|purge|0)
    systemctl stop meteor && systemctl disable meteor
    rm -f /lib/systemd/system/meteor.service
    rm -rf /opt/meteor
    userdel -rf meteor
    groupdel meteor
    ;;
  *)
    echo "postrm called with unknown argument: $1" >&2
    exit 1
    ;;
esac
